language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
scripts:
  - npm run lint
  - npm run compile
  - npm run test
  - npm run coverage
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
